// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfsga8By_cJ_RMlHjx8N8kxlcNb4Qcclw',
    appId: '1:318632021517:web:db1901fb10133335d58f44',
    messagingSenderId: '318632021517',
    projectId: 'water-level-751b7',
    authDomain: 'water-level-751b7.firebaseapp.com',
    databaseURL: 'https://water-level-751b7-default-rtdb.firebaseio.com',
    storageBucket: 'water-level-751b7.appspot.com',
    measurementId: 'G-8Y4235F0K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYENG3vy0Q6l45Zo9T7aSEXjL19DuCkfA',
    appId: '1:318632021517:android:f072da139442ad7cd58f44',
    messagingSenderId: '318632021517',
    projectId: 'water-level-751b7',
    databaseURL: 'https://water-level-751b7-default-rtdb.firebaseio.com',
    storageBucket: 'water-level-751b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTG8sKuaYrpgOaV79pA2BwJoFTGsv2Bqk',
    appId: '1:318632021517:ios:9d16f375453db368d58f44',
    messagingSenderId: '318632021517',
    projectId: 'water-level-751b7',
    databaseURL: 'https://water-level-751b7-default-rtdb.firebaseio.com',
    storageBucket: 'water-level-751b7.appspot.com',
    iosBundleId: 'com.aries.waterlevelMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTG8sKuaYrpgOaV79pA2BwJoFTGsv2Bqk',
    appId: '1:318632021517:ios:b227cadde8352173d58f44',
    messagingSenderId: '318632021517',
    projectId: 'water-level-751b7',
    databaseURL: 'https://water-level-751b7-default-rtdb.firebaseio.com',
    storageBucket: 'water-level-751b7.appspot.com',
    iosBundleId: 'com.aries.waterlevelMobile.RunnerTests',
  );
}
